In [2]:
# 1. Take 3 lists a,b,c containing 2 integers each. Create a numpy array of these lists and
#         apply numpy functions including dtype, ndim, size, shape, and itemsize.

import numpy as np
a=[1,2]
b=[4,5]
c=[7,8]

dp=np.array([a,b,c])
dp

array([[1, 2],
       [4, 5],
       [7, 8]])

In [8]:
print(dp.dtype)
print(dp.ndim)
print(dp.size)
print(dp.shape)
print(dp.itemsize)


int64
2
6
(3, 2)
8


2. Assume, you are given two lists:
(i) a = [1,2,3,4,5], b = [6,7,8,9]
(ii) a = [10,20,30], b = [10,50,30,70]
(iii) a = [1,3,5,7], b = [2,3,5,8]
(a) The task is to create a list which has all the elements of a and b in one
dimension.
(b) The task is to create a list which has all the elements of a and b in one dimension
without repetition

In [9]:
import numpy as np

# Define the lists
a1 = [1, 2, 3, 4, 5]
b1 = [6, 7, 8, 9]
a2 = [10, 20, 30]
b2 = [10, 50, 30, 70]
a3 = [1, 3, 5, 7]
b3 = [2, 3, 5, 8]

# Combine the lists using NumPy
combined1 = np.concatenate((a1, b1))
combined2 = np.concatenate((a2, b2))
combined3 = np.concatenate((a3, b3))

# Print the results
print("Combined array 1:", combined1)
print("Combined array 2:", combined2)
print("Combined array 3:", combined3)


Combined array 1: [1 2 3 4 5 6 7 8 9]
Combined array 2: [10 20 30 10 50 30 70]
Combined array 3: [1 3 5 7 2 3 5 8]


In [10]:
# Combine the lists without repetition using NumPy
unique_combined1 = np.unique(np.concatenate((a1, b1)))
unique_combined2 = np.unique(np.concatenate((a2, b2)))
unique_combined3 = np.unique(np.concatenate((a3, b3)))

# Print the results
print("Unique combined array 1:", unique_combined1)
print("Unique combined array 2:", unique_combined2)
print("Unique combined array 3:", unique_combined3)


Unique combined array 1: [1 2 3 4 5 6 7 8 9]
Unique combined array 2: [10 20 30 50 70]
Unique combined array 3: [1 2 3 5 7 8]


Create an array that can store height of 15 students by taking user input and replace all
elements of array which are greater than 6.5 by 7.0 .

In [ ]:
num_students = 15

heights = []

for i in range(num_students):
    height_value = float(input(f"Enter height of student {i+1}: "))
    heights.append(height_value)

heights_array = np.array(heights)

heights_array[heights_array > 6.5] = 7.0

print("Updated heights array:", heights_array)


In [40]:
import numpy as np

numbers = np.arange(1, 82)

matrix = numbers.reshape(9, 9).astype(float)

matrix[matrix <= 25] = np.nan

print(matrix)


[[nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan nan nan]
 [nan nan nan nan nan nan nan 26. 27.]
 [28. 29. 30. 31. 32. 33. 34. 35. 36.]
 [37. 38. 39. 40. 41. 42. 43. 44. 45.]
 [46. 47. 48. 49. 50. 51. 52. 53. 54.]
 [55. 56. 57. 58. 59. 60. 61. 62. 63.]
 [64. 65. 66. 67. 68. 69. 70. 71. 72.]
 [73. 74. 75. 76. 77. 78. 79. 80. 81.]]
